# This is a basic workflow that is manually triggered

name: Setup EC2 Instance workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Create instance
      run: | 
        aws ec2 run-instances \
        --image-id ami-0b183bb1259186479 \
        --count 1 \
        --instance-type t4g.small \
        --key-name MC-Key \
        --security-group-ids sg-04761a3598cb75765 \
        --query "Instances[0].PublicIpAddress" \
        --output text \
        --tag-specifications 'ResourceType=instance, Tags=[{Key=Name, Value=Minecraft-Server-AUTO}]'
